version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    user: "redis:redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
  outline:
    image: outline:v001
    command:
      - sh 
      - -c 
      - |
        yarn sequelize db:migrate --env=production-ssl-disabled
        yarn start
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/outline
    depends_on:
      - postgres
      - redis
      - s3
